{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2024-02-04T14:54:46.103657Z",
     "start_time": "2024-02-04T14:54:44.170053Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (2.2.0)\r\n",
      "Requirement already satisfied: pyarrow in ./.venv/lib/python3.12/site-packages (15.0.0)\r\n",
      "Requirement already satisfied: selenium in ./.venv/lib/python3.12/site-packages (4.17.2)\r\n",
      "Requirement already satisfied: numpy<2,>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (1.26.3)\r\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.8.2)\r\n",
      "Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas) (2024.1)\r\n",
      "Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas) (2023.4)\r\n",
      "Requirement already satisfied: urllib3[socks]<3,>=1.26 in ./.venv/lib/python3.12/site-packages (from selenium) (2.2.0)\r\n",
      "Requirement already satisfied: trio~=0.17 in ./.venv/lib/python3.12/site-packages (from selenium) (0.24.0)\r\n",
      "Requirement already satisfied: trio-websocket~=0.9 in ./.venv/lib/python3.12/site-packages (from selenium) (0.11.1)\r\n",
      "Requirement already satisfied: certifi>=2021.10.8 in ./.venv/lib/python3.12/site-packages (from selenium) (2024.2.2)\r\n",
      "Requirement already satisfied: typing_extensions>=4.9.0 in ./.venv/lib/python3.12/site-packages (from selenium) (4.9.0)\r\n",
      "Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\r\n",
      "Requirement already satisfied: attrs>=20.1.0 in ./.venv/lib/python3.12/site-packages (from trio~=0.17->selenium) (23.2.0)\r\n",
      "Requirement already satisfied: sortedcontainers in ./.venv/lib/python3.12/site-packages (from trio~=0.17->selenium) (2.4.0)\r\n",
      "Requirement already satisfied: idna in ./.venv/lib/python3.12/site-packages (from trio~=0.17->selenium) (3.6)\r\n",
      "Requirement already satisfied: outcome in ./.venv/lib/python3.12/site-packages (from trio~=0.17->selenium) (1.3.0.post0)\r\n",
      "Requirement already satisfied: sniffio>=1.3.0 in ./.venv/lib/python3.12/site-packages (from trio~=0.17->selenium) (1.3.0)\r\n",
      "Requirement already satisfied: wsproto>=0.14 in ./.venv/lib/python3.12/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)\r\n",
      "Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in ./.venv/lib/python3.12/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)\r\n",
      "Requirement already satisfied: h11<1,>=0.9.0 in ./.venv/lib/python3.12/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)\r\n",
      "\r\n",
      "\u001B[1m[\u001B[0m\u001B[34;49mnotice\u001B[0m\u001B[1;39;49m]\u001B[0m\u001B[39;49m A new release of pip is available: \u001B[0m\u001B[31;49m23.2.1\u001B[0m\u001B[39;49m -> \u001B[0m\u001B[32;49m23.3.2\u001B[0m\r\n",
      "\u001B[1m[\u001B[0m\u001B[34;49mnotice\u001B[0m\u001B[1;39;49m]\u001B[0m\u001B[39;49m To update, run: \u001B[0m\u001B[32;49mpip install --upgrade pip\u001B[0m\r\n"
     ]
    }
   ],
   "source": [
    "!pip install pandas pyarrow selenium"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "95333e0a5ba4e464",
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-02-04T14:54:46.724293Z",
     "start_time": "2024-02-04T14:54:46.107103Z"
    }
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from selenium import webdriver as webdriver\n",
    "from selenium.webdriver import DesiredCapabilities, Chrome, ChromeOptions\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.proxy import Proxy, ProxyType\n",
    "import json\n",
    "\n",
    "HOMEPAGE = \"https://www.cognomix.it/origine-cognomi-italiani/A\"\n",
    "\n",
    "PROXY_LIST = [\n",
    "    \"185.25.205.141:80\",\n",
    "    \"93.94.90.189:4145\",\n",
    "    \"77.242.130.73:5678\",\n",
    "    \"94.198.213.252:5678\",\n",
    "    \"77.72.32.15:59605\",\n",
    "    \"178.250.70.218:1088\",\n",
    "    \"93.94.90.180:4145\",\n",
    "    \"89.40.227.114:58120\",\n",
    "    \"94.198.215.22:52477\",\n",
    "    \"185.61.169.67:4145\",\n",
    "    \"88.51.214.182:80\",\n",
    "    \"79.7.101.98:5678\",\n",
    "    \"212.3.188.33:8080\",\n",
    "    \"89.40.227.114:44793\",\n",
    "    \"77.242.132.113:5678\",\n",
    "    \"77.242.177.57:3128\",\n",
    "    \"109.70.206.42:5678\",\n",
    "    \"185.109.184.150:56067\",\n",
    "    \"185.109.184.150:63819\"\n",
    "]\n",
    "\n",
    "letters = [\n",
    "    {\"letter\": 'A', \"size\": 14},\n",
    "    {\"letter\": 'B', \"size\": 24},\n",
    "    {\"letter\": 'C', \"size\": 28},\n",
    "    {\"letter\": 'D', \"size\": 16},\n",
    "    {\"letter\": 'E', \"size\": 2},\n",
    "    {\"letter\": 'F', \"size\": 12},\n",
    "    {\"letter\": 'G', \"size\": 15},\n",
    "    {\"letter\": 'I', \"size\": 4},\n",
    "    {\"letter\": 'L', \"size\": 10},\n",
    "    {\"letter\": 'M', \"size\": 20},\n",
    "    {\"letter\": 'N', \"size\": 4},\n",
    "    {\"letter\": 'O', \"size\": 3},\n",
    "    {\"letter\": 'P', \"size\": 19},\n",
    "    {\"letter\": 'Q', \"size\": 1},\n",
    "    {\"letter\": 'R', \"size\": 9},\n",
    "    {\"letter\": 'S', \"size\": 19},\n",
    "    {\"letter\": 'T', \"size\": 10},\n",
    "    {\"letter\": 'U', \"size\": 1},\n",
    "    {\"letter\": 'V', \"size\": 7},\n",
    "    {\"letter\": 'Z', \"size\": 5}\n",
    "]\n",
    "\n",
    "data = []"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e070ca17e7a65e14",
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-02-04T14:54:46.730879Z",
     "start_time": "2024-02-04T14:54:46.725271Z"
    }
   },
   "outputs": [],
   "source": [
    "def get_data(url):\n",
    "    # PROXY = PROXY_LIST[0]\n",
    "    PROXY = \"http://103.168.155.116:80\"\n",
    "    \n",
    "    # webdriver.DesiredCapabilities.CHROME['proxy']={\n",
    "    #     \"httpProxy\": PROXY,\n",
    "    #     \"ftpProxy\": PROXY,\n",
    "    #     \"sslProxy\": PROXY,\n",
    "    #     \"proxyType\": \"MANUAL\",\n",
    "    # }\n",
    "    \n",
    "    # webdriver.DesiredCapabilities.CHROME['acceptSslCerts'] = True\n",
    "    browser_options = ChromeOptions()\n",
    "    # browser_options.add_argument(\"--proxy-server=%s\" % PROXY)\n",
    "    driver = Chrome(options=browser_options)\n",
    "    \n",
    "    \n",
    "    \n",
    "    driver.get(url)\n",
    "\n",
    "    list_element = driver.find_elements(By.XPATH, '//ul/li/a[contains(@href, \"cognomix.it/origine-cognome/\")]')\n",
    "\n",
    "    for item in list_element:\n",
    "        name = item.text.split(\"-\")[0]\n",
    "        data.append({'surname': name})\n",
    "\n",
    "    driver.quit()\n",
    "    return data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1c7cf3af0f20d5a6",
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-02-04T14:54:46.731245Z",
     "start_time": "2024-02-04T14:54:46.728953Z"
    }
   },
   "outputs": [],
   "source": [
    "def export_data(data,name):\n",
    "    df = pd.DataFrame(data)\n",
    "    df.to_csv(f\"{name}.csv\", index=False)\n",
    "    with open(f\"{name}.json\", 'w', encoding='utf-8') as f:\n",
    "            json.dump(data, f, ensure_ascii=False, indent=4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5732dd81558fd847",
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-02-04T15:10:23.842778Z",
     "start_time": "2024-02-04T14:54:46.732764Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n",
      "Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known\n"
     ]
    }
   ],
   "source": [
    "for list in letters:\n",
    "    for i in range(1, list[\"size\"] + 1):\n",
    "        new_url = f\"https://www.cognomix.it/origine-cognomi-italiani/{list['letter']}/{i}\"\n",
    "        get_data(url=new_url)\n",
    "    export_data(data,\"surname\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a9dfadafcf8e3f1a",
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-02-04T15:10:23.846473Z",
     "start_time": "2024-02-04T15:10:23.843482Z"
    }
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
